# -*- coding: utf-8 -*-
"""pdspbl.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JJu1U4bIycaA1TPZ6wwqhU5W1WSUFevN
"""

# PDS PRACTICAL 1 TO 14- COMBINED PROGRAM

import math
import numpy as np
import pandas as pd
from scipy import stats
from bs4 import BeautifulSoup


# 1. Libraries / Environment
def practical1():
    print("Python Environment Ready")
    print("NumPy, Pandas, Matplotlib, SciPy, Seaborn, sklearn installed")


# 2. Student Details
def practical2():
    r = input("Roll No: ")
    n = input("Name: ")
    b = input("Branch: ")
    s = input("Semester: ")
    e = input("Email: ")
    m = input("Mobile: ")
    print(r, n, b, s, e, m)


# 3. Marks, Percentage, Grade
def practical3():
    marks = [float(input(f"Subject {i+1}: ")) for i in range(5)]
    total = sum(marks)
    per = total / 5

    if per >= 90: grade = "A"
    elif per >= 80: grade = "B"
    elif per >= 70: grade = "C"
    elif per >= 40: grade = "D"
    else: grade = "F"

    print("Total:", total, "Percentage:", per)
    print("Grade:", grade, "Status:", "Pass" if per >= 40 else "Fail")


# 4. Membership and Bitwise Operators
def practical4():
    club = input("Club: ")
    hostel = input("Hostel Required (Yes/No): ")

    clubs = ["Coding", "Robotics", "Sports", "Music"]
    print("Club Eligible:", club in clubs)

    lib, lab, host = 1, 2, 4
    permission = lib | lab | host if hostel.lower() == "yes" else lib | lab

    print("Permission Code:", permission)
    print("Library:", bool(permission & lib))
    print("Laboratory:", bool(permission & lab))
    print("Hostel:", bool(permission & host))


# 5. Data Structures
def practical5():
    subjects = ["Python", "DBMS", "OS"]
    semesters = (3, 4, 5)
    clubs = {"Coding", "Sports"}
    student = {"Roll": 101, "Branch": "CE"}
    marks = np.array([75, 80, 70])
    name = "Neel"

    subjects.append("AI")
    clubs.add("Music")
    student["Roll"] = 102

    print(subjects)
    print(semesters)
    print(clubs)
    print(student)
    print(marks, name)


# 6. Attendance Function
def practical6():
    a = [int(input(f"Day {i+1} (1=Present,0=Absent): ")) for i in range(5)]

    def attendance(x):
        return sum(x) / len(x) * 100

    p = attendance(a)
    print("Attendance:", p)
    print("Rounded Up:", math.ceil(p))


# 7. Pickle / Exception
def practical7():
    import pickle

    data = {"Roll": 101, "Name": "Neel"}

    try:
        with open("student.dat", "wb") as f:
            pickle.dump(data, f)

        with open("student.dat", "rb") as f:
            print("Record:", pickle.load(f))

    except Exception as e:
        print("Error:", e)


# 8. Text File CRUD
def practical8():
    file = "student.txt"
    r = input("Roll: ")
    n = input("Name: ")

    with open(file, "a") as f:
        f.write(r + "," + n + "\n")

    print("\nRecords:")
    with open(file) as f:
        data = f.readlines()
        print("".join(data))

    search = input("Search Roll: ")
    print("Found:", any(x.startswith(search + ",") for x in data))


# 9. CSV File CRUD
def practical9():
    import csv

    file = "student.csv"
    r = input("Roll: ")
    n = input("Name: ")

    with open(file, "a", newline="") as f:
        csv.writer(f).writerow([r, n])

    with open(file) as f:
        rows = list(csv.reader(f))

    print("Records:", rows)
    search = input("Search Roll: ")
    print([x for x in rows if x[0] == search])


# 10. MySQL CRUD
def practical10():
    import mysql.connector

    db = mysql.connector.connect(
        host="localhost", user="root", password="1234",
        database="college"
    )
    c = db.cursor()

    c.execute("CREATE TABLE IF NOT EXISTS student(roll INT, name VARCHAR(30))")
    c.execute("INSERT INTO student VALUES(101,'Neel')")
    db.commit()

    c.execute("SELECT * FROM student")
    print(c.fetchall())

    c.execute("UPDATE student SET name='ABC' WHERE roll=101")
    c.execute("DELETE FROM student WHERE roll=101")
    db.commit()
    db.close()


# 11. NumPy Marks
def practical11():
    a = np.array([70, 80, 60, 90, 75])

    print("Marks:", a)
    print("Total:", np.sum(a))
    print("Percentage:", np.mean(a))

    print("Percentile of 75:",
          stats.percentileofscore(a, 75))


# 12. SciPy Statistics
def practical12():
    a = np.array([50, 60, 70, 70, 80, 90])

    print("Mean:", np.mean(a))
    print("Median:", np.median(a))
    print("Mode:", stats.mode(a, keepdims=True).mode[0])
    print("Std:", np.std(a))
    print("Variance:", np.var(a))
    print("Skewness:", stats.skew(a))
    print("Kurtosis:", stats.kurtosis(a))

    ci = stats.t.interval(.95, len(a)-1,
                           loc=np.mean(a),
                           scale=stats.sem(a))
    print("Confidence Interval:", ci)


# 13. Pandas Statistics
def practical13():
    df = pd.DataFrame({
        "Python": [70, 80, 60, 90, 75],
        "DBMS": [65, 75, 70, 85, 80]
    })

    print(df)
    print("Mean:\n", df.mean())
    print("Median:\n", df.median())
    print("Mode:\n", df.mode().iloc[0])
    print("Std:\n", df.std())
    print("Variance:\n", df.var())
    print("Skewness:\n", df.skew())


# 14. BeautifulSoup + Pandas Merge
def practical14():
    html = """
    <table>
    <tr><th>Roll</th><th>Name</th></tr>
    <tr><td>101</td><td>Neel</td></tr>
    <tr><td>102</td><td>Rahul</td></tr>
    </table>
    """

    soup = BeautifulSoup(html, "html.parser")
    rows = soup.find_all("tr")[1:]

    info = [[r.find_all("td")[0].text,
             r.find_all("td")[1].text] for r in rows]

    students = pd.DataFrame(info, columns=["Roll", "Name"])

    marks = pd.DataFrame({
        "Roll": ["101", "102"],
        "Marks": [80, 75]
    })

    print(pd.merge(students, marks, on="Roll"))

# 15. Moving Average Calculation
def practical15():
    data = [100, 120, 110, 130, 150, 140, 160]

    df = pd.DataFrame({
        "Day": range(1, 8),
        "Sales": data
    })

    # 3-day moving average
    df["Moving_Average"] = df["Sales"].rolling(window=3).mean()

    print("\nSales Data:")
    print(df)

    print("\n3-Day Moving Average:")
    print(df[["Day", "Sales", "Moving_Average"]])


# MENU
while True:
    print("\n===== PDS PRACTICAL 1-15 =====")
    print("1-15 : Run Practical")
    print("0    : Exit")

    ch = int(input("Enter choice: "))

    if ch == 0:
        break

    functions = {
        1: practical1, 2: practical2, 3: practical3,
        4: practical4, 5: practical5, 6: practical6,
        7: practical7, 8: practical8, 9: practical9,
        10: practical10, 11: practical11, 12: practical12,
        13: practical13, 14: practical14, 15: practical15
    }

    if ch in functions:
        functions[ch]()
    else:
        print("Invalid choice")